In [40]:
#First of all import the necessary files
import numpy as np
import pandas as pd

In [41]:
#lets import the data
url = "https://gist.githubusercontent.com/sarchak/b87ad2be315ce05f7a047550646f3c41/raw/0c7d83608111f74f212398fc0d2a704e4f8dc499/diamonds.csv"
df = pd.read_csv(url, error_bad_lines=False)

In [42]:
#lets dispaly the dataframe
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [43]:
#check for null values if any
null_columns=df.columns[df.isnull().any()]
df[null_columns].isnull().sum()

Series([], dtype: float64)

In [44]:
# Q1 lets find the median price of the entire dataset.
median_price=np.median(df["price"])
print(median_price)

2401.0

In [45]:
# Q2 Lets find the mean price.
mean_price=np.mean(df["price"])
print(mean_price)

3932.799721913237

In [46]:
# Q3 Now lets find the median price in between carate 1.5 and 3.0
df_in_between=df.loc[(df["carat"] > 1.5) & (df["carat"] <3.0)]
median_price_in_btw=np.median(df_in_between["price"])
median_price_in_btw

12549.0

In [47]:
# Q4 Now count the premium cut diamond with clarity of VVS1 or I1 or IF
df_in_Premium_VVS1_I1_IF=df.loc[(df["cut"] =="Premium") & ((df["clarity"] =="VVS1") | (df["clarity"] =="I1") | (df["clarity"] =="IF"))]
df_in_Premium_VVS1_I1_IF["cut"].count()

1051

In [48]:
# Q5 Now lets find the mean carat size of diamond between price $3500 - $7000
df_in_between_price=df.loc[(df["price"] > 3500) & (df["carat"] <7000)]
mean_carat_size_between_price= np.mean(df_in_between_price["carat"])
mean_carat_size_between_price

1.2698143656716026

In [49]:
df2=df.groupby(["cut","color","clarity"]).price.mean()

In [53]:
df2

cut        color  clarity
Fair       D      I1         7383.000000
                  IF         1619.666667
                  SI1        4273.344828
                  SI2        4355.142857
                  VS1        2921.200000
                                ...
Very Good  J      SI2        5992.898438
                  VS1        4339.591667
                  VS2        5325.548913
                  VVS1       3175.526316
                  VVS2       5960.448276
Name: price, Length: 276, dtype: float64

In [51]:
df3=df2.unstack()

In [52]:
df3

clarity                   I1            IF          SI1          SI2  \
cut       color
Fair      D      7383.000000   1619.666667  4273.344828  4355.142857
          E      2095.222222           NaN  3901.153846  4172.384615
          F      2543.514286   2344.000000  3784.686747  4520.112360
          G      3187.471698   1488.000000  3579.362319  5665.150000
          H      4212.961538           NaN  5195.800000  6022.406593
          I      3501.000000           NaN  4574.966667  6658.022222
          J      5795.043478           NaN  4553.928571  5131.814815
Good      D      3490.750000  10030.333333  3021.172996  3595.295964
          E      4398.130435   1519.222222  3162.132394  3785.490099
          F      2569.526316   3132.866667  3261.454212  4426.786070
          G      3195.789474   4060.136364  4129.328502  4776.411043
          H      3849.714286   5948.750000  4179.285106  5529.778481
          I      4175.444444   1749.333333  4742.945455  6933.012346
          J      3794.500000   2738.000000  4627.625000  5306.113208
Ideal     D      3526.923077   6567.178571  2490.459350  3142.047753
          E      3559.388889   3258.936709  2883.808094  3891.302772
          F      3903.452381   2153.708955  3710.322368  4335.507726
          G      4044.437500   2206.030550  3441.107576  4612.086420
          H      5415.184211   1982.765487  4769.988204  5589.473333
          I      4103.294118   1502.621053  5178.565476  7191.912409
          J      9454.000000   2489.000000  5115.674897  6555.172727
Premium   D      3818.750000   9056.500000  3236.377698  4351.085511
          E      3199.266667   4525.444444  3362.625407  4489.930636
          F      3554.558824   3617.580645  4040.467105  4747.089866
          G      4051.521739   3311.114943  4303.348057  5617.205285
          H      3904.347826   3384.750000  5707.722137  6718.946257
          I      5044.625000   2358.565217  6092.092643  7148.483974
          J      4577.230769   7026.000000  5726.578947  7550.285714
Very Good D      2622.800000  10298.260870  3234.931174  4425.458599
          E      3443.545455   4332.744186  3228.175719  4279.447191
          F      4252.923077   4677.074627  3574.291592  4249.758017
          G      3194.812500   3525.240506  3481.871308  4699.269113
          H      5258.833333   2647.689655  4933.945155  6112.413994
          I      6045.125000   4093.894737  5195.301676  6621.600000
          J      4478.375000   1074.125000  5026.543956  5992.898438

clarity                  VS1          VS2         VVS1         VVS2
cut       color
Fair      D      2921.200000  4512.880000  4473.000000  3607.000000
          E      3307.928571  3041.714286  4115.333333  3119.307692
          F      4103.060606  3400.471698  4679.800000  4018.200000
          G      3497.622222  5384.444444  2216.333333  3099.058824
          H      4604.750000  5110.926829  4115.000000  3481.727273
          I      4500.480000  3856.125000  4194.000000  2994.625000
          J      5906.187500  4067.826087  1691.000000  2998.000000
Good      D      3556.581395  3588.461538  2586.230769  2345.640000
          E      3712.775281  3772.018750  1905.953488  3390.153846
          F      2787.507576  3790.543478  2189.514286  3192.360000
          G      4302.427632  4140.713542  2705.195122  3310.466667
          H      3819.116883  4433.043478  1719.709677  2428.000000
          I      4597.165049  5956.563636  2650.954545  2758.000000
          J      3662.826923  4803.166667  4633.000000  4371.153846
Ideal     D      2576.039886  2111.927174  2705.777778  3619.014085
          E      2175.797639  2163.323944  2205.519403  2556.335306
          F      3504.001623  3317.204778  2611.234091  3323.628846
          G      4116.918153  4310.035165  2909.198653  3795.651163
          H      3613.325482  4039.125899  1915.984663  2591.155709
          I      3944.421569  4663.383562  2034.396648  2858.679775
          J      4734.427861  4867.133621  2000.172414  4121.925926
Premium   D      4178.045802  2919.356932  3771.000000  3888.436170
          E      3721.695205  3070.394277  2699.857143  2940.942149
          F      4758.037931  4221.466882  3969.325000  4099.465753
          G      4435.823322  4556.255201  2933.654971  4323.570909
          H      3949.336310  5553.875940  1453.758929  2651.262712
          I      5339.366516  7156.346032  1831.083333  3190.768293
          J      5817.261438  6175.559406  7244.375000  6423.352941
Very Good D      2955.480000  3145.194175  2987.730769  2615.297872
          E      3089.358362  3329.497018  1997.447059  2041.684564
          F      3880.802048  3995.944206  2826.540230  3461.911647
          G      3770.150463  4426.816284  2719.331579  3711.784768
          H      3750.198444  4620.220745  2042.191304  2768.144828
          I      5276.970732  5754.642336  2056.420290  3059.887324
          J      4339.591667  5325.548913  3175.526316  5960.448276